// src/data/alliance-data.js
// Sources: Official alliance charters, NATO, CSTO, SCO websites

export const ALLIANCES = [
  {
    id: 'nato',
    name: 'NATO',
    fullName: 'North Atlantic Treaty Organization',
    founded: 1949,
    color: '#1a6ed8',
    glowColor: 'rgba(26,110,216,0.4)',
    type: 'Military',
    description: 'Primary Western collective defense alliance. Article 5 mutual defense pact.',
    members: ['USA','CAN','GBR','FRA','DEU','ITA','ESP','PRT','NLD','BEL','LUX','NOR','DNK','ISL','TUR','GRC','POL','CZE','HUN','SVK','SVN','BGR','ROU','EST','LVA','LTU','ALB','HRV','MNE','MKD','FIN','SWE'],
    hq: 'Brussels, Belgium',
  },
  {
    id: 'csto',
    name: 'CSTO',
    fullName: 'Collective Security Treaty Organization',
    founded: 2002,
    color: '#c62828',
    glowColor: 'rgba(198,40,40,0.4)',
    type: 'Military',
    description: 'Russian-led post-Soviet collective security alliance. Mutual defense pact.',
    members: ['RUS','BLR','KAZ','KGZ','TJK','ARM'],
    hq: 'Moscow, Russia',
  },
  {
    id: 'sco',
    name: 'SCO',
    fullName: 'Shanghai Cooperation Organisation',
    founded: 2001,
    color: '#e65100',
    glowColor: 'rgba(230,81,0,0.4)',
    type: 'Political-Military',
    description: 'China & Russia led security/political bloc. World\'s largest regional organization by area.',
    members: ['CHN','RUS','IND','PAK','KAZ','KGZ','TJK','UZB','IRN'],
    hq: 'Beijing, China',
  },
  {
    id: 'aukus',
    name: 'AUKUS',
    fullName: 'Australia–United Kingdom–United States',
    founded: 2021,
    color: '#00838f',
    glowColor: 'rgba(0,131,143,0.4)',
    type: 'Military',
    description: 'Trilateral security pact focused on nuclear-powered submarines and advanced tech sharing.',
    members: ['AUS','GBR','USA'],
    hq: 'No permanent HQ',
  },
  {
    id: 'quad',
    name: 'QUAD',
    fullName: 'Quadrilateral Security Dialogue',
    founded: 2007,
    color: '#6a1b9a',
    glowColor: 'rgba(106,27,154,0.4)',
    type: 'Political-Military',
    description: 'Indo-Pacific strategic forum countering Chinese influence. Informal but increasingly military.',
    members: ['USA','IND','AUS','JPN'],
    hq: 'No permanent HQ',
  },
  {
    id: 'arab_league',
    name: 'Arab League',
    fullName: 'League of Arab States',
    founded: 1945,
    color: '#2e7d32',
    glowColor: 'rgba(46,125,50,0.4)',
    type: 'Political',
    description: '22-member pan-Arab political organization. Joint Defense Treaty for collective security.',
    members: ['SAU','EGY','IRQ','JOR','LBN','SYR','YEM','LBY','SDN','TUN','MAR','DZA','KWT','ARE','QAT','BHR','OMN','MRT','SOM','COM','DJI','PSE'],
    hq: 'Cairo, Egypt',
  },
  {
    id: 'au',
    name: 'African Union',
    fullName: 'African Union',
    founded: 2002,
    color: '#558b2f',
    glowColor: 'rgba(85,139,47,0.4)',
    type: 'Political',
    description: '55-member continental union. African Standby Force for peacekeeping operations.',
    members: ['DZA','AGO','BEN','BWA','BFA','BDI','CMR','CPV','CAF','TCD','COM','COD','COG','CIV','DJI','EGY','GNQ','ERI','SWZ','ETH','GAB','GMB','GHA','GIN','GNB','KEN','LSO','LBR','LBY','MDG','MWI','MLI','MRT','MUS','MAR','MOZ','NAM','NER','NGA','RWA','STP','SEN','SLE','SOM','ZAF','SSD','SDN','TZA','TGO','TUN','UGA','ZMB','ZWE','SYC','ERI'],
    hq: 'Addis Ababa, Ethiopia',
  },
  {
    id: 'five_eyes',
    name: 'Five Eyes',
    fullName: 'Five Eyes Intelligence Alliance',
    founded: 1946,
    color: '#00695c',
    glowColor: 'rgba(0,105,92,0.4)',
    type: 'Intelligence',
    description: 'Most comprehensive signals intelligence sharing agreement in the world.',
    members: ['USA','GBR','CAN','AUS','NZL'],
    hq: 'No permanent HQ',
  },
];

export default ALLIANCES;