// src/data/nuclear-data.js
// Sources: FAS Nuclear Notebook, SIPRI Yearbook 2025, Bulletin of Atomic Scientists,
// Arms Control Association, declassified US/Russian START data, IISS Military Balance 2025/2026

export const NUCLEAR_SUMMARY = {
  totalWarheads:    12241,
  deployedWarheads: 3912,
  countries:        9,
  lastUpdated:      '2025/2026',
  source:           'FAS Nuclear Notebook / SIPRI 2025 / Bulletin 2026',
};

export const NUCLEAR_COUNTRIES = [

  // ════════════════════════════════════════════════════════════════
  // RUSSIA
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'RUS', name: 'Russia', flag: '🇷🇺',
    color: '#e53935',
    firstTest: { date: '29 Aug 1949', location: 'Semipalatinsk, Kazakhstan', codename: 'Joe-1', yield: '22 kt' },
    treaties: ['NPT', 'START I', 'New START', 'CTBT (signed)', 'INF (withdrawn 2019)'],
    doctrine: 'Nuclear escalation as strategic deterrent; "escalate to de-escalate" posture. Reserves right to first use if state existence threatened.',
    warheads: { deployed: 1718, reserve: 2591, retired: 1150, total: 5459 },
    deliverySystems: ['ICBM', 'SLBM', 'Strategic Bomber', 'Tactical Nuclear', 'Cruise Missile'],
    notableTests: 'Tsar Bomba (50 MT) — largest ever detonated, 30 Oct 1961',
    weapons: [
      {
        id: 'rs28',
        name: 'RS-28 Sarmat', nato: 'SS-X-30 Satan 2',
        type: 'ICBM', status: 'Active (limited)',
        image: 'https://missilethreat.csis.org/wp-content/uploads/2017/05/rs-28.jpg',
        yield: { min: 350, max: 750, unit: 'kt', warheads: '10–15 MIRV' },
        range: 18000, speed: 'Mach 20+',
        blast_radius: { fireball: 3.4, heavy_blast: 7.7, moderate_blast: 17, thermal: 45, radiation: 10 },
        length: '35.5m', diameter: '3m', weight: '208,100 kg',
        firstDeployed: 2022, quantity: '~10 (IOC)',
        cost: '$~20M per missile',
        propulsion: 'Liquid-fueled, two-stage',
        payload: 'Up to 10 MIRVed warheads or hypersonic glide vehicles',
        launchMethod: 'Silo-based cold launch (mortar ejection then ignition)',
        launchSteps: ['Launch order from President via Cheget briefcase', 'Perimeter (Dead Hand) system authorization', 'Cold-gas mortar ejects missile from silo', 'First stage ignites at ~30m altitude', 'Warheads deploy at apogee ~1,000km altitude', 'MIRV bus maneuvers to engage multiple targets'],
        features: ['Hypersonic glide vehicle capable', 'Designed to defeat missile defense', 'Can fly polar or depressed trajectories', 'Nuclear-powered boost vehicle option (Burevestnik)'],
        description: 'Russia\'s newest heavy ICBM, replacing the R-36M Voevoda. Designed specifically to overwhelm US missile defense systems with hypersonic maneuvering warheads.',
      },
      {
        id: 'rs12m2',
        name: 'RS-12M2 Topol-M', nato: 'SS-27 Sickle B',
        type: 'ICBM (road-mobile & silo)', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/19-03-2012-Parade-rehearsal_-_Topol-M.jpg/960px-19-03-2012-Parade-rehearsal_-_Topol-M.jpg',
        yield: { min: 550, max: 800, unit: 'kt', warheads: '1 (or 3 MIRV on RS-24)' },
        range: 11000, speed: 'Mach 22',
        blast_radius: { fireball: 1.7, heavy_blast: 5.3, moderate_blast: 12, thermal: 35, radiation: 8 },
        length: '22.7m', diameter: '1.9m', weight: '47,200 kg',
        firstDeployed: 1997, quantity: '~78',
        cost: '$8M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'Single 800kt warhead or RS-24 Yars variant with 3–6 MIRVs',
        launchMethod: 'TEL (Transporter Erector Launcher) or silo',
        launchSteps: ['Presidential launch authorization via Cheget', 'TEL deploys off-road to hide location', 'Missile erected to vertical', 'Solid fuel first stage ignites', 'All three stages burn in ~3 minutes', 'Warhead bus deploys at 200km altitude'],
        features: ['Road-mobile — survives first strike', 'Hard to track from satellite', 'Maneuvering re-entry vehicle', '10-minute flight to USA'],
        description: 'Russia\'s primary ICBM workhorse. Road-mobile variant is nearly impossible to locate and destroy in a first strike, guaranteeing second-strike capability.',
      },
      {
        id: 'r30',
        name: 'R-30 Bulava', nato: 'SS-NX-32',
        type: 'SLBM', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Yuri_Dolgorukiy_successfully_launched_a_Bulava_ballistic_missile_%28cropped%29.jpg',
        yield: { min: 100, max: 150, unit: 'kt', warheads: '6–10 MIRV' },
        range: 9300, speed: 'Mach 20',
        blast_radius: { fireball: 0.9, heavy_blast: 3.2, moderate_blast: 8, thermal: 22, radiation: 5 },
        length: '12.1m', diameter: '2m', weight: '36,800 kg',
        firstDeployed: 2013, quantity: '~176 (on Borei submarines)',
        cost: '$~5M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: '6–10 MIRVed warheads 100–150kt each',
        launchMethod: 'Submarine cold launch from Borei-class SSBN, depth up to 55m',
        launchSteps: ['SSBN receives ELF radio launch order while submerged', 'Captain and XO both authenticate launch codes', 'Missile ejected by gas pressure from tube', 'First stage ignites after clearing the water', 'Submarine immediately changes depth and heading', 'MIRV bus deploys warheads over ~1,500km footprint'],
        features: ['Launched from submerged submarine', 'Virtually undetectable at launch', 'Shorter than US Trident but similar capability', 'Troubled development — 7 early test failures'],
        description: 'Russia\'s primary sea-based nuclear deterrent, deployed on Borei-class submarines. Each Borei carries 16 Bulava missiles, giving one submarine the capacity to destroy 96+ cities.',
      },
      {
        id: 'kh102',
        name: 'Kh-102', nato: 'AS-23B',
        type: 'Air-launched Cruise Missile', status: 'Active',
        image: 'https://cdn-iladncp.nitrocdn.com/HqlEixensysOTCVgzDQPqXypWdYAZutW/assets/images/optimized/wp-content/uploads/2017/10/10e49051c3b14e7455f959cd1e4279df.EyG2AroXEAEwGmM-1024x683.jpg',
        yield: { min: 250, max: 450, unit: 'kt', warheads: '1' },
        range: 4500, speed: 'Mach 0.77',
        blast_radius: { fireball: 1.3, heavy_blast: 4.1, moderate_blast: 9, thermal: 28, radiation: 7 },
        length: '7.45m', diameter: '0.51m', weight: '2,300 kg',
        firstDeployed: 2012, quantity: '~500',
        cost: '$~1.5M per missile',
        propulsion: 'Turbofan engine',
        payload: '250–450kt nuclear warhead',
        launchMethod: 'Air-launched from Tu-95MS or Tu-160 strategic bomber',
        launchSteps: ['Tu-160 or Tu-95 bomber takes off from Engels or Ukrainka base', 'Bomber flies to stand-off launch point (outside enemy air defense)', 'Crew receives authorization codes via secure datalink', 'Missile dropped from internal rotary launcher', 'Turbofan engine starts, terrain-following flight begins', 'Warhead detonates at preset altitude over target'],
        features: ['Extreme low altitude flight (terrain following)', 'Fired from outside air defense range', 'Conventional variant (Kh-101) used in Ukraine war', 'Accuracy: ~5–10m CEP'],
        description: 'Russia\'s premier nuclear-armed cruise missile. Flies below radar at treetop level for thousands of kilometers. The conventional Kh-101 has been used extensively against Ukraine.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // UNITED STATES
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'USA', name: 'United States', flag: '🇺🇸',
    color: '#1565c0',
    firstTest: { date: '16 Jul 1945', location: 'Trinity Site, New Mexico', codename: 'Trinity', yield: '21 kt' },
    treaties: ['NPT', 'New START', 'CTBT (signed, not ratified)', 'INF (withdrawn 2019)'],
    doctrine: 'Nuclear deterrence; "No First Use" debated but not official policy. Guarantees extended deterrence to NATO and Pacific allies.',
    warheads: { deployed: 1770, reserve: 1930, retired: 1477, total: 5177 },
    deliverySystems: ['ICBM', 'SLBM', 'Strategic Bomber', 'Tactical Nuclear (B61)', 'Cruise Missile'],
    notableTests: 'Castle Bravo — 15 MT, largest US test, 1 Mar 1954. Contaminated Marshall Islands.',
    weapons: [
      {
        id: 'lgm30',
        name: 'LGM-30G Minuteman III',
        type: 'ICBM', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/LGM-30-Minuteman-II.jpg',
        yield: { min: 300, max: 475, unit: 'kt', warheads: '1 (de-MIRVed from 3)' },
        range: 13000, speed: 'Mach 23',
        blast_radius: { fireball: 1.5, heavy_blast: 4.8, moderate_blast: 11, thermal: 30, radiation: 7 },
        length: '18.2m', diameter: '1.85m', weight: '35,400 kg',
        firstDeployed: 1970, quantity: '400',
        cost: '$7M per missile (plus $100B modernization program)',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'W87-1 warhead, 300–475kt',
        launchMethod: 'Underground hardened silo (600 psi blast resistant)',
        launchSteps: ['Presidential Emergency Action Document (NSPD) authorizes launch', 'Two-man rule: both officers turn keys simultaneously', 'Launch Control Center sends encoded launch message', 'Silo closure doors blow open via explosive bolts', 'Solid fuel first stage ignites — missile accelerates to 24,000 km/h in 3 minutes', 'Warhead re-enters atmosphere at Mach 23, reaches target in ~30 min from US'],
        features: ['Only land-based ICBM in US arsenal', 'Kept on "hair-trigger" alert', '400 missiles in WY, MT, ND silos', 'Being replaced by LGM-35 Sentinel by 2030'],
        description: 'The backbone of US land-based nuclear deterrence since 1970. Despite its age, it remains one of the most accurate ICBMs ever deployed. Replacement Sentinel program is $100B+.',
      },
      {
        id: 'ugm133',
        name: 'UGM-133 Trident II D5',
        type: 'SLBM', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Trident_II_missile_image.jpg/500px-Trident_II_missile_image.jpg',
        yield: { min: 100, max: 475, unit: 'kt', warheads: '8 MIRV (up to 14)' },
        range: 12000, speed: 'Mach 24',
        blast_radius: { fireball: 1.5, heavy_blast: 4.8, moderate_blast: 11, thermal: 30, radiation: 7 },
        length: '13.4m', diameter: '2.11m', weight: '59,090 kg',
        firstDeployed: 1990, quantity: '~280 (on 14 Ohio-class SSBNs)',
        cost: '$31M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'Up to 8 W76-1 (100kt) or W88 (475kt) warheads per missile',
        launchMethod: 'Submarine launch from Ohio-class SSBN at depth up to 90m',
        launchSteps: ['SSBN receives Emergency Action Message via VLF radio', 'Two-man rule authentication by captain and XO', 'Missile tube flooded and pressurized', 'Gas generator ejects missile — it travels 30m underwater before igniting', 'First stage ignites at surface breakout', 'Three stages burn; MIRV bus deploys warheads across hundreds of km'],
        features: ['Circular error probable (CEP): 90m — extremely accurate', 'A single Ohio SSBN can carry 192 warheads (24 missiles × 8)', 'Near impossible to detect when submerged', 'Shared with UK Royal Navy'],
        description: 'Widely considered the world\'s most capable nuclear weapon. Its accuracy rivals ICBMs while being essentially invulnerable to first strike. One Ohio-class submarine carries more destructive power than all bombs used in WWII.',
      },
      {
        id: 'b61',
        name: 'B61-12 Gravity Bomb',
        type: 'Tactical/Strategic Nuclear Bomb', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/B61_nuclear_bomb.jpg/1280px-B61_nuclear_bomb.jpg',
        yield: { min: 0.3, max: 50, unit: 'kt', warheads: '1 (dial-a-yield)' },
        range: 0, speed: 'subsonic (dropped)',
        blast_radius: { fireball: 0.3, heavy_blast: 1.2, moderate_blast: 3, thermal: 10, radiation: 3 },
        length: '3.58m', diameter: '0.33m', weight: '315 kg',
        firstDeployed: 1968, quantity: '~230 (100 in Europe, NATO sharing)',
        cost: '$28M per bomb (B61-12 upgrade)',
        propulsion: 'None — gravity bomb with precision tail kit',
        payload: 'Variable yield: 0.3, 1.5, 10, or 50kt selectable',
        launchMethod: 'Dropped from F-35A, B-2A Spirit, or NATO dual-capable aircraft',
        launchSteps: ['Pilot receives authentication codes from command', 'Permissive Action Link (PAL) code entered — arms weapon', 'Aircraft enters target area at low altitude for accuracy', 'Bomb released — tail fin kit guides to GPS coordinates', 'Fuzing options: airburst, surface, or earth-penetrating (bunker buster)', 'Delayed arming allows aircraft escape time'],
        features: ['Dial-a-yield: 0.3kt to 50kt selectable in cockpit', 'Earth-penetrating capability — destroys buried bunkers', 'Deployed in 5 NATO countries (Belgium, Germany, Italy, Netherlands, Turkey)', 'B61-12 upgrade adds guided tail kit — accuracy improved 10x'],
        description: 'The most widely deployed US nuclear weapon. Its presence in Europe under NATO nuclear sharing makes it a unique political and military tool. The guided B61-12 can now penetrate hardened bunkers.',
      },
      {
        id: 'agm86b',
        name: 'AGM-86B ALCM',
        type: 'Air-launched Cruise Missile', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/AGM-86_ALCM.JPEG/960px-AGM-86_ALCM.JPEG',
        yield: { min: 5, max: 150, unit: 'kt', warheads: '1 W80-1' },
        range: 2400, speed: 'Mach 0.73',
        blast_radius: { fireball: 0.9, heavy_blast: 3.0, moderate_blast: 7, thermal: 20, radiation: 5 },
        length: '6.32m', diameter: '0.69m', weight: '1,430 kg',
        firstDeployed: 1982, quantity: '~528',
        cost: '$~1M per missile',
        propulsion: 'Turbofan (Williams F107)',
        payload: 'W80-1 warhead, 5–150kt variable yield',
        launchMethod: 'Air-launched from B-52H Stratofortress',
        launchSteps: ['B-52H takes off from Minot or Barksdale AFB', 'Aircraft flies to standoff launch position', 'Up to 20 ALCMs released from external pylons and internal rotary launcher', 'Turbofan engine starts; wings unfold', 'TERCOM (terrain contour matching) + GPS guides missile', 'Warhead detonates at programmed coordinates'],
        features: ['Can be launched 2,400km from target — outside air defense range', 'Terrain-following flight (below radar)', 'Each B-52H can carry 20 ALCMs', 'Being replaced by LRSO (Long Range Stand-Off missile)'],
        description: 'Allows B-52s to strike targets without entering defended airspace. Has been in service over 40 years and remains effective due to its extreme range and low-altitude penetration.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // CHINA
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'CHN', name: 'China', flag: '🇨🇳',
    color: '#c62828',
    firstTest: { date: '16 Oct 1964', location: 'Lop Nur, Xinjiang', codename: '596 / Chic-1', yield: '22 kt' },
    treaties: ['NPT', 'CTBT (signed)'],
    doctrine: 'No First Use (NFU) declared policy. Minimum deterrence shifting to "limited deterrence." Rapid expansion underway — estimated 1,000+ warheads by 2030.',
    warheads: { deployed: 24, reserve: 576, retired: 0, total: 600 },
    deliverySystems: ['ICBM', 'SLBM', 'Bomber', 'Tactical Nuclear', 'Hypersonic Glide Vehicle'],
    notableTests: 'Test No. 6 — first Chinese thermonuclear test, 17 Jun 1967, 3.3 MT',
    weapons: [
      {
        id: 'df41',
        name: 'DF-41 (Dongfeng-41)', nato: 'CSS-X-20',
        type: 'ICBM (road-mobile & silo)', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/120%E7%A7%92%E7%9C%8B%E5%A4%A7%E9%98%85%E5%85%B5%E9%9C%87%E6%92%BC%E7%9E%AC%E9%97%B4%EF%BC%811.png/960px-120%E7%A7%92%E7%9C%8B%E5%A4%A7%E9%98%85%E5%85%B5%E9%9C%87%E6%92%BC%E7%9E%AC%E9%97%B4%EF%BC%811.png',
        yield: { min: 200, max: 1000, unit: 'kt', warheads: '10 MIRV' },
        range: 14000, speed: 'Mach 25',
        blast_radius: { fireball: 2.0, heavy_blast: 5.8, moderate_blast: 13, thermal: 38, radiation: 9 },
        length: '21m', diameter: '2.25m', weight: '80,000 kg',
        firstDeployed: 2017, quantity: '~72–108',
        cost: '$~12M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'Up to 10 MIRV warheads 200–1,000kt each',
        launchMethod: 'Road-mobile TEL or underground silo (new silo fields in Gansu/Xinjiang)',
        launchSteps: ['CMC (Central Military Commission) Chairman authorizes launch', 'PLA Rocket Force unit deploys TEL to pre-surveyed firing point', 'Silo lid opens or TEL erects missile to 90°', 'Cold-gas launch ejects missile before ignition', 'Solid fuel first stage ignites at ~20m', 'MIRV bus deploys warheads targeting US mainland in ~30 minutes'],
        features: ['Can reach entire US mainland', 'Road-mobile — extremely hard to track', 'China building 300+ new silos (2021 satellite discovery)', 'Hypersonic glide vehicle tests conducted'],
        description: 'China\'s most capable ICBM. Recent satellite imagery reveals China is building hundreds of new missile silos, suggesting a dramatic arsenal expansion. The DF-41 is central to this buildup.',
      },
      {
        id: 'df5b',
        name: 'DF-5B (Dongfeng-5B)',
        type: 'ICBM (silo-based)', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Dongfeng-5B_head.JPG/960px-Dongfeng-5B_head.JPG',
        yield: { min: 4000, max: 5000, unit: 'kt', warheads: '3–8 MIRV' },
        range: 13000, speed: 'Mach 23',
        blast_radius: { fireball: 4.5, heavy_blast: 10, moderate_blast: 22, thermal: 60, radiation: 15 },
        length: '32.6m', diameter: '3.35m', weight: '183,000 kg',
        firstDeployed: 1981, quantity: '~20',
        cost: '$~15M per missile',
        propulsion: 'Liquid-fueled, two-stage',
        payload: '3–8 MIRVed warheads, 4–5 MT each',
        launchMethod: 'Underground silo, requires fueling before launch (15–30 min)',
        launchSteps: ['Launch order from CMC via hardened command post', 'Liquid propellant loaded (RP-1 / N2O4) — slow process', 'Silo blast door opens via explosive bolts', 'Engines ignite — missile reaches orbit altitude', 'MIRV bus releases warheads over target', 'Each warhead re-enters at ~7km/s'],
        features: ['Largest warhead in Chinese arsenal (4–5 MT)', 'Liquid fuel requires pre-launch preparation — detectable', 'Being replaced by DF-41 solid-fuel missiles', 'Used primarily to hold US cities at risk'],
        description: 'China\'s oldest ICBM still in service, but carries the largest warheads. Its liquid fuel requirement makes it vulnerable, but the enormous yield compensates — a single warhead could destroy any city on earth.',
      },
      {
        id: 'df26',
        name: 'DF-26 (Dongfeng-26)', nato: 'CSS-18',
        type: 'IRBM / Anti-ship Ballistic Missile', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Dong-Feng_26.JPG/960px-Dong-Feng_26.JPG',
        yield: { min: 1200, max: 1800, unit: 'kt', warheads: '1 (nuclear or conventional)' },
        range: 4000, speed: 'Mach 18',
        blast_radius: { fireball: 2.5, heavy_blast: 6.5, moderate_blast: 14, thermal: 40, radiation: 10 },
        length: '14m', diameter: '1.4m', weight: '20,000 kg',
        firstDeployed: 2016, quantity: '~200–250',
        cost: '$~5M per missile',
        propulsion: 'Solid-fuel, two-stage',
        payload: 'Nuclear (1.2–1.8 MT) or conventional precision strike',
        launchMethod: 'Road-mobile TEL',
        launchSteps: ['PLA Rocket Force receives targeting data', 'TEL deploys to launch site within hours', 'Missile erected and targeting data uploaded', 'Launch — maneuvering warhead makes interception difficult', 'Can target US bases in Guam (within range)', 'Anti-ship variant uses radar/optical terminal guidance'],
        features: ['Called "Guam Killer" — puts US base in Guam within range', 'Dual nuclear/conventional capability', 'Can target aircraft carriers — unique capability', 'Maneuvering reentry vehicle defeats Aegis defense'],
        description: 'A uniquely versatile weapon — the only nuclear-armed ballistic missile specifically designed to target aircraft carriers. Its range covers Guam and all US Pacific bases, making it central to China\'s anti-access strategy.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // UNITED KINGDOM
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'GBR', name: 'United Kingdom', flag: '🇬🇧',
    color: '#1565c0',
    firstTest: { date: '3 Oct 1952', location: 'Monte Bello Islands, Australia', codename: 'Hurricane', yield: '25 kt' },
    treaties: ['NPT', 'CTBT', 'New START (observer)'],
    doctrine: 'Minimum credible deterrent. Sea-based only since 1998. Continuous At-Sea Deterrence (CASD) — one SSBN always on patrol since 1969.',
    warheads: { deployed: 120, reserve: 105, retired: 0, total: 225 },
    deliverySystems: ['SLBM (Trident II D5 only)'],
    notableTests: 'Last test 1991. Shared US Nevada Test Site.',
    weapons: [
      {
        id: 'trident_uk',
        name: 'Trident II D5 (UK)',
        type: 'SLBM', status: 'Active',
        image: 'https://cdn-iladncp.nitrocdn.com/HqlEixensysOTCVgzDQPqXypWdYAZutW/assets/images/optimized/wp-content/uploads/2016/10/c76c8645ba5ca1c4dadb346c604c9379.TD5.jpg',
        yield: { min: 100, max: 100, unit: 'kt', warheads: '8 (max 40 per boat)' },
        range: 12000, speed: 'Mach 24',
        blast_radius: { fireball: 0.9, heavy_blast: 3.2, moderate_blast: 7.5, thermal: 21, radiation: 5 },
        length: '13.4m', diameter: '2.11m', weight: '59,090 kg',
        firstDeployed: 1994, quantity: '~48 operational missiles (shared US pool)',
        cost: '$31M per missile (leased from US)',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'Up to 8 W76-1 (100kt) warheads',
        launchMethod: 'Vanguard-class SSBN from depth up to 90m',
        launchSteps: ['PM authorizes through "Letters of Last Resort" (pre-written, sealed)', 'SSBN receives launch order via VLF radio', 'Captain authenticates with XO using dual keys', 'Tube flooded; gas ejection launches missile underwater', 'Missile breaks surface and first stage ignites', 'MIRV bus deploys warheads over target area'],
        features: ['UK owns warheads but missiles are US-pool (leased)', 'Continuous patrol since 1969 — CASD never broken', '"Letters of Last Resort" — handwritten PM instructions in safe', 'Replacing Vanguard-class with Dreadnought-class (2030s)'],
        description: 'The UK\'s sole nuclear delivery system. One Vanguard-class submarine is always on patrol, giving the UK an invulnerable second-strike capability. The PM\'s personal handwritten letters in each sub\'s safe order what to do if the UK is destroyed.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // FRANCE
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'FRA', name: 'France', flag: '🇫🇷',
    color: '#1565c0',
    firstTest: { date: '13 Feb 1960', location: 'Reggane, Algeria', codename: 'Gerboise Bleue', yield: '70 kt' },
    treaties: ['NPT', 'CTBT'],
    doctrine: 'Strict minimum deterrence. Total independence from NATO nuclear command (withdrew 1966). Will not share doctrine details.',
    warheads: { deployed: 280, reserve: 10, retired: 0, total: 290 },
    deliverySystems: ['SLBM', 'Air-launched Cruise Missile (ASMP-A)'],
    notableTests: 'Last tests 1996, Mururoa Atoll. Conducted 210 total tests.',
    weapons: [
      {
        id: 'm51',
        name: 'M51.2 SLBM',
        type: 'SLBM', status: 'Active',
        image: 'https://cdn-iladncp.nitrocdn.com/HqlEixensysOTCVgzDQPqXypWdYAZutW/assets/images/optimized/wp-content/uploads/2020/07/13ce0a1bba32ba671e22eb124eda98bd.m51-2-723x1024.jpg',
        yield: { min: 100, max: 300, unit: 'kt', warheads: '6–10 MIRV (TN75)' },
        range: 10000, speed: 'Mach 22',
        blast_radius: { fireball: 0.9, heavy_blast: 3.2, moderate_blast: 7.5, thermal: 21, radiation: 5 },
        length: '12m', diameter: '2.3m', weight: '52,000 kg',
        firstDeployed: 2010, quantity: '~80 missiles (on 4 Triomphant-class SSBNs)',
        cost: '$~80M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: '6–10 TN75 warheads, 100kt each with penetration aids',
        launchMethod: 'Le Triomphant-class SSBN, completely independent French design',
        launchSteps: ['President of Republic authorizes via secure channel', 'Order transmitted to SSBN at sea', 'French-designed two-person authentication', 'Cold-gas ejection from tube', 'Ignition at sea surface', 'TN75 warheads deploy with decoys to defeat ABM systems'],
        features: ['Entirely French-designed — no US components', 'Penetration aids (decoys) to defeat missile defenses', 'TN75 warheads feature maneuvering capability', 'France maintains full operational independence'],
        description: 'France\'s sea-based deterrent, entirely designed and built in France without US cooperation. Paris refused to share nuclear technology or doctrine with NATO, maintaining complete strategic independence.',
      },
      {
        id: 'asmpa',
        name: 'ASMP-A (Air-Sol Moyenne Portée Amélioré)',
        type: 'Air-launched Cruise Missile', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/ASMP-A_P1220887.jpg/500px-ASMP-A_P1220887.jpg',
        yield: { min: 300, max: 300, unit: 'kt', warheads: '1 TNA warhead' },
        range: 500, speed: 'Mach 3',
        blast_radius: { fireball: 1.5, heavy_blast: 4.5, moderate_blast: 10, thermal: 29, radiation: 7 },
        length: '5.38m', diameter: '0.38m', weight: '860 kg',
        firstDeployed: 2009, quantity: '~54',
        cost: '$~3M per missile',
        propulsion: 'Solid booster + ramjet sustainer',
        payload: 'TNA thermonuclear warhead, 300kt',
        launchMethod: 'Air-launched from Rafale F3 (replaces Mirage 2000N)',
        launchSteps: ['Rafale crew receives authorization from Elysée Palace', 'Mission parameters programmed into missile', 'Rafale penetrates at low altitude to avoid radar', 'ASMP-A launched at stand-off range', 'Ramjet accelerates to Mach 3 — nearly impossible to intercept', 'TNA detonates at airburst or surface burst'],
        features: ['Mach 3 makes it nearly uncatchable by current SAMs', 'Deployed on carrier-based Rafale (nuclear-armed carrier aviation)', 'Being replaced by ASN4G (hypersonic, Mach 8+) in 2030s', 'France is only country with carrier-based nuclear aircraft'],
        description: 'France\'s airborne nuclear deterrent. The ramjet-powered ASMP-A flies at Mach 3, making it extremely difficult to intercept. France is the only country deploying nuclear-armed aircraft from an aircraft carrier.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // PAKISTAN
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'PAK', name: 'Pakistan', flag: '🇵🇰',
    color: '#2e7d32',
    firstTest: { date: '28 May 1998', location: 'Chagai District, Balochistan', codename: 'Chagai-I', yield: '25–36 kt (est.)' },
    treaties: ['None — not NPT signatory'],
    doctrine: 'First use explicitly reserved against India. "Full Spectrum Deterrence" — tactical to strategic. Rapid expansion.',
    warheads: { deployed: 0, reserve: 170, retired: 0, total: 170 },
    deliverySystems: ['MRBM', 'IRBM', 'Cruise Missile', 'Tactical Battlefield Nuclear'],
    notableTests: 'Chagai-I (5 tests in one day) and Chagai-II. Pakistan tested 6 devices in 1998 response to India.',
    weapons: [
      {
        id: 'shaheen3',
        name: 'Shaheen-III',
        type: 'MRBM', status: 'Active',
        image: 'https://imrmedia.in/wp-content/uploads/2022/04/Pak-Shaheen-III-ballistic-missile.jpg',
        yield: { min: 10, max: 40, unit: 'kt', warheads: '1' },
        range: 2750, speed: 'Mach 15',
        blast_radius: { fireball: 0.7, heavy_blast: 2.5, moderate_blast: 6, thermal: 17, radiation: 4 },
        length: '17.5m', diameter: '1.4m', weight: '25,000 kg',
        firstDeployed: 2015, quantity: '~20–25',
        cost: '$~5M per missile',
        propulsion: 'Solid-fuel, two-stage',
        payload: '10–40kt nuclear warhead',
        launchMethod: 'Road-mobile TEL',
        launchSteps: ['NCA (National Command Authority) authorization', 'SPD (Strategic Plans Division) releases custody', 'TEL deploys to pre-surveyed launch site', 'Missile erected and programmed', 'Launch — can reach all of India including Andaman Islands', 'Single warhead detonates over target'],
        features: ['Range covers all of India plus Andaman & Nicobar Islands', 'Specifically designed to target Indian carrier groups', 'Pakistan\'s longest-range missile', 'MIRV development reported'],
        description: 'Pakistan\'s longest-range ballistic missile, explicitly designed to hold all of India at risk including distant island territories. Development was accelerated after India began sea-basing its nuclear forces.',
      },
      {
        id: 'nasr',
        name: 'Nasr (Hatf-IX)',
        type: 'Tactical Battlefield Nuclear', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Nasr_missile_at_parade.webp/960px-Nasr_missile_at_parade.webp.png',
        yield: { min: 0.2, max: 5, unit: 'kt', warheads: '1' },
        range: 70, speed: 'Mach 4',
        blast_radius: { fireball: 0.2, heavy_blast: 0.8, moderate_blast: 2, thermal: 6, radiation: 2 },
        length: '3.5m', diameter: '0.29m', weight: '175 kg',
        firstDeployed: 2013, quantity: '~50+ (estimated)',
        cost: '$~0.5M per missile',
        propulsion: 'Solid-fuel',
        payload: '0.2–5kt tactical nuclear warhead',
        launchMethod: 'Multiple launch rocket system (MLRS) — 4 tubes per vehicle',
        launchSteps: ['Field commander requests use authorization from NCA', 'SPD delivers assembled weapon to field unit', 'MLRS fires salvo against advancing Indian armored columns', 'Sub-kiloton airburst destroys tanks over wide area', 'Creates nuclear contamination zone halting advance', 'Designed to stop India\'s Cold Start rapid offensive'],
        features: ['Designed specifically to defeat India\'s Cold Start doctrine', 'Sub-kiloton yield — tactical, not city-destroying', 'Raises nuclear threshold questions — blurs tactical/strategic line', 'Most controversial weapon in South Asian nuclear balance', 'Stored in forward positions near border — high accident risk'],
        description: 'The most destabilizing weapon in South Asia. Nasr is a battlefield nuclear weapon intended to be used against advancing Indian tank columns. Its short range and sub-kiloton yield blur the line between conventional and nuclear warfare.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // INDIA
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'IND', name: 'India', flag: '🇮🇳',
    color: '#e65100',
    firstTest: { date: '18 May 1974', location: 'Pokhran, Rajasthan', codename: 'Smiling Buddha', yield: '8 kt' },
    treaties: ['None — not NPT signatory. Signed CTBT.'],
    doctrine: 'No First Use (NFU) — firm policy. Massive retaliation if attacked. "Credible minimum deterrence."',
    warheads: { deployed: 0, reserve: 180, retired: 0, total: 180 },
    deliverySystems: ['MRBM', 'IRBM', 'SLBM (developing)', 'Fighter aircraft'],
    notableTests: 'Operation Shakti (1998) — 5 tests including thermonuclear device. Yield disputed (India claims 45kt; seismic estimate 12–25kt).',
    weapons: [
      {
        id: 'agni5',
        name: 'Agni-V',
        type: 'ICBM-class IRBM', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Agni_V_Ballistic_missile_successfully_launched_on_December_10%2C_2018.jpg/500px-Agni_V_Ballistic_missile_successfully_launched_on_December_10%2C_2018.jpg',
        yield: { min: 150, max: 300, unit: 'kt', warheads: '1 (MIRV development underway)' },
        range: 5500, speed: 'Mach 24',
        blast_radius: { fireball: 1.2, heavy_blast: 3.8, moderate_blast: 9, thermal: 26, radiation: 6 },
        length: '17.5m', diameter: '2m', weight: '50,000 kg',
        firstDeployed: 2018, quantity: '~20–25',
        cost: '$~9M per missile',
        propulsion: 'Solid-fuel, three-stage',
        payload: '150–300kt nuclear warhead; MIRV variant (Agni-V MIRV) tested 2024',
        launchMethod: 'Canisterized road-mobile TEL',
        launchSteps: ['Political authorization from PM/Cabinet Committee on Security', 'Strategic Forces Command activates unit', 'Canisterized missile deployed on TEL', 'Raised to vertical; targeting data uploaded', 'Launch — covers all of China including Beijing', 'Warhead deployed at apogee over China/target'],
        features: ['Puts all Chinese cities within range', 'Canisterized — ready to fire quickly', 'MIRV tested March 2024 — significantly increases capability', 'Road-mobile — survivable'],
        description: 'India\'s first true intercontinental-range missile, developed primarily to counter China. The successful MIRV test in 2024 marks a major escalation in South Asian and Indo-Pacific nuclear dynamics.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // ISRAEL
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'ISR', name: 'Israel', flag: '🇮🇱',
    color: '#1565c0',
    firstTest: { date: 'Unknown (suspected 22 Sep 1979)', location: 'South Atlantic (Vela Incident)', codename: 'Vela Incident', yield: '2–3 kt (suspected)' },
    treaties: ['None — not NPT signatory. Never confirmed nuclear capability.'],
    doctrine: 'Deliberate ambiguity ("Nuclear Opacity") — neither confirms nor denies. "Samson Option" — use if state faces existential destruction.',
    warheads: { deployed: 0, reserve: 90, retired: 0, total: 90 },
    deliverySystems: ['Ballistic missile (Jericho)', 'Aircraft', 'Submarine-launched (suspected)'],
    notableTests: 'No confirmed tests. Vela satellite anomaly 1979 suspected joint Israel-South Africa test.',
    weapons: [
      {
        id: 'jericho3',
        name: 'Jericho III',
        type: 'ICBM', status: 'Active (unconfirmed)',
        image: 'https://warhistory.org/media/2024/12/jericho_3.jpg',
        yield: { min: 150, max: 400, unit: 'kt', warheads: '1–3 (suspected MRV)' },
        range: 11500, speed: 'Mach 21',
        blast_radius: { fireball: 1.2, heavy_blast: 3.8, moderate_blast: 8.5, thermal: 25, radiation: 6 },
        length: '15.5m', diameter: '1.56m', weight: '30,000 kg',
        firstDeployed: 2008, quantity: '~25–50 (estimated)',
        cost: 'Classified',
        propulsion: 'Solid-fuel, three-stage',
        payload: 'Estimated 150–400kt; suspected MIRV/MRV capability',
        launchMethod: 'Underground hardened silo or mobile launcher',
        launchSteps: ['Cabinet decision under existential threat', '"Samson Option" authorization chain activated', 'Israel does not confirm procedures', 'Believed to have hardened command bunkers', 'Multiple delivery vectors provide redundancy', 'Can reach Iran, Russia, Europe from Israeli territory'],
        features: ['Range covers Iran, Russia, and most of Europe', 'Israel maintains official ambiguity — never confirmed', 'Believed to have submarine-launched nuclear cruise missiles', '"Samson Option" — use even in defeat if state threatened'],
        description: 'Israel\'s most capable nuclear delivery system — though Israel officially maintains nuclear opacity and has never confirmed its existence. Intelligence assessments universally agree Israel has a sophisticated nuclear arsenal. The Samson Option doctrine threatens annihilation even in defeat.',
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // NORTH KOREA
  // ════════════════════════════════════════════════════════════════
  {
    iso3: 'PRK', name: 'North Korea', flag: '🇰🇵',
    color: '#b71c1c',
    firstTest: { date: '9 Oct 2006', location: 'Punggye-ri Nuclear Test Site', codename: 'Test 1', yield: '0.7–2 kt' },
    treaties: ['None — withdrew from NPT 2003'],
    doctrine: 'Survival and regime preservation. First use authorized if "fundamental interests threatened." Kim Jong-un declared nuclear force law in 2022.',
    warheads: { deployed: 0, reserve: 50, retired: 0, total: 50 },
    deliverySystems: ['ICBM', 'MRBM', 'SLBM (testing)', 'Tactical Nuclear'],
    notableTests: 'Test 6 (3 Sep 2017) — ~250kt thermonuclear device. Largest DPRK test.',
    weapons: [
      {
        id: 'hwasong17',
        name: 'Hwasong-17',
        type: 'ICBM', status: 'Active',
        image: 'https://www.missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/north-korea/hwasong-17-kn-27/',
        yield: { min: 100, max: 300, unit: 'kt', warheads: '1 (MRV testing)' },
        range: 15000, speed: 'Mach 22',
        blast_radius: { fireball: 1.5, heavy_blast: 4.5, moderate_blast: 10, thermal: 29, radiation: 7 },
        length: '25m', diameter: '2.9m', weight: '~145,000 kg',
        firstDeployed: 2022, quantity: '~5–10',
        cost: 'Classified / state-produced',
        propulsion: 'Liquid-fuel, two-stage (Paektusan engines)',
        payload: 'Single large warhead or suspected MRV development',
        launchMethod: '11-axle TEL (world\'s largest road-mobile missile)',
        launchSteps: ['Kim Jong-un personal authorization', 'Korean People\'s Army Strategic Force activates unit', 'Giant 11-axle TEL deploys to launch site', 'Liquid propellant loading (hours)', 'Missile erected; guidance system activated', 'Liftoff — can reach any city in continental US in ~33 min'],
        features: ['World\'s largest road-mobile ICBM', 'Can reach Washington D.C. — demonstrated Nov 2022', 'Displayed with "super-large nuclear warhead" per KCNA', 'North Korea claimed hydrogen bomb warhead capability', 'Liquid fuel limits rapid launch — takes hours to fuel'],
        description: 'The "Monster ICBM" — the largest road-mobile intercontinental ballistic missile ever built. Its Nov 2022 test demonstrated the capability to reach any point in the continental United States. North Korea claims it carries a thermonuclear warhead.',
      },
      {
        id: 'hwasong11da',
        name: 'Hwasong-11Da (KN-25)',
        type: 'Tactical Nuclear Missile', status: 'Active',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/KN-25_TEL.webp/960px-KN-25_TEL.webp.png',
        yield: { min: 0.5, max: 10, unit: 'kt', warheads: '1 tactical' },
        range: 400, speed: 'Mach 6',
        blast_radius: { fireball: 0.4, heavy_blast: 1.5, moderate_blast: 4, thermal: 11, radiation: 3 },
        length: '~6m', diameter: '0.6m', weight: '~3,000 kg',
        firstDeployed: 2023, quantity: 'Unknown (many suspected)',
        cost: 'Classified',
        propulsion: 'Solid-fuel',
        payload: 'Small tactical nuclear warhead',
        launchMethod: 'Multiple rocket launcher',
        launchSteps: ['Field commander authorization from Kim Jong-un', 'MRL unit deploys near DMZ', 'Missile fired in salvos', 'Low-yield nuclear airburst over Seoul, Osan, or USFK base', 'Designed to destroy South Korean command and US reinforcements', 'Creates nuclear contamination zone'],
        features: ['Designed to decapitate South Korean military command', 'Could strike Seoul in under 2 minutes from DMZ', 'Declared operational with nuclear warheads 2023', 'Most dangerous short-range nuclear threat in Asia'],
        description: 'North Korea\'s tactical nuclear weapon, explicitly designed to destroy US and South Korean military targets near the DMZ. Its short range and quick launch time make it one of the most destabilizing weapons on the Korean Peninsula.',
      },
    ],
  },
];

export default NUCLEAR_COUNTRIES;